# Generated by Django 2.2.7 on 2019-12-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191207_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='college',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rollnumber',
            field=models.CharField(default='NA', max_length=20),
        ),
    ]
