# Generated by Django 2.2.7 on 2019-12-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191207_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firstname',
            field=models.CharField(default='NA', max_length=24),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastname',
            field=models.CharField(default='NA', max_length=24),
        ),
    ]
