# Generated by Django 2.2.7 on 2019-12-06 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191207_0113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='firstname',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lastname',
        ),
    ]
