# Generated by Django 2.2.7 on 2019-12-06 18:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191206_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 6, 18, 51, 31, 172615, tzinfo=utc)),
        ),
    ]
