# Generated by Django 2.2.7 on 2019-12-06 19:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191207_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 6, 19, 35, 0, 300192, tzinfo=utc)),
        ),
    ]
