# Generated by Django 2.2.7 on 2019-12-06 19:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191207_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 6, 19, 43, 29, 328071, tzinfo=utc)),
        ),
    ]
