# Generated by Django 2.2.7 on 2019-12-06 19:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191207_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 6, 19, 45, 38, 695624, tzinfo=utc)),
        ),
    ]
