# Generated by Django 2.2.7 on 2019-12-07 13:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191207_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 7, 13, 5, 5, 295928, tzinfo=utc)),
        ),
    ]
