# Generated by Django 2.2.7 on 2019-12-10 13:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191207_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 10, 13, 55, 51, 245408, tzinfo=utc)),
        ),
    ]
