# Generated by Django 2.2.7 on 2019-12-10 14:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20191210_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 10, 14, 20, 32, 279609, tzinfo=utc)),
        ),
    ]
