# Generated by Django 2.2.7 on 2019-12-11 17:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20191211_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 11, 17, 21, 10, 681899, tzinfo=utc)),
        ),
    ]
