# Generated by Django 2.2.7 on 2019-12-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50)),
                ('cateogory', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=1000)),
                ('sample_input', models.CharField(max_length=50)),
                ('sample_output', models.CharField(max_length=50)),
                ('testcase_inputs', models.FileField(upload_to='')),
                ('testcase_outputs', models.FileField(upload_to='')),
            ],
        ),
    ]
