# Generated by Django 2.2.7 on 2019-12-11 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=24)),
                ('rollnumber', models.CharField(default='', max_length=20)),
                ('college', models.CharField(default='', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('submitted_code', models.TextField(max_length=10000)),
                ('total_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Slug', models.SlugField()),
                ('Title', models.CharField(max_length=120)),
                ('Description', models.TextField(max_length=120)),
                ('College', models.CharField(max_length=120)),
                ('Duration', models.DurationField()),
                ('Date', models.CharField(default='', max_length=20)),
                ('Active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Slug', models.SlugField()),
                ('Title', models.CharField(max_length=120)),
                ('Type', models.CharField(max_length=120)),
                ('Description', models.TextField(max_length=320)),
                ('sample_inputs', models.TextField(max_length=50)),
                ('sample_outputs', models.TextField(max_length=50)),
                ('challenge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.Challenge')),
            ],
        ),
        migrations.CreateModel(
            name='testcases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input1', models.TextField(default='', max_length=1000)),
                ('input2', models.TextField(default='', max_length=1000)),
                ('input3', models.TextField(default='', max_length=1000)),
                ('input4', models.TextField(default='', max_length=1000)),
                ('input5', models.TextField(default='', max_length=1000)),
                ('output1', models.TextField(default='', max_length=1000)),
                ('output2', models.TextField(default='', max_length=1000)),
                ('output3', models.TextField(default='', max_length=1000)),
                ('output4', models.TextField(default='', max_length=1000)),
                ('output5', models.TextField(default='', max_length=1000)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='challenge.Question')),
            ],
        ),
        migrations.CreateModel(
            name='submittedcodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission', models.TextField(max_length=10000)),
                ('score', models.IntegerField(default=0)),
                ('Challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.Challenge')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.Candidate')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='test_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.Challenge'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
