# Generated by Django 2.2.4 on 2019-12-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='score',
        ),
        migrations.AddField(
            model_name='candidate',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submittedcodes',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
