# Generated by Django 2.2.7 on 2019-12-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='tenth_percentage',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='twelveth_percentage',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='Description',
            field=models.TextField(max_length=520),
        ),
    ]
