# Generated by Django 2.2.7 on 2019-12-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_auto_20191210_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='Description',
            field=models.TextField(max_length=120),
        ),
        migrations.AlterField(
            model_name='question',
            name='sample_inputs',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='sample_output',
            field=models.TextField(max_length=50),
        ),
    ]
