# Generated by Django 2.2.7 on 2019-12-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_auto_20191212_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='branch',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='graduation_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='mobile_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='tenth_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='twelveth_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
