# Generated by Django 2.2.7 on 2019-12-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_auto_20191213_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='ug_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
