# Generated by Django 2.2.7 on 2019-12-13 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_candidate_ug_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='tenth_percentage',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='twelveth_percentage',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='ug_percentage',
        ),
    ]
