# Generated by Django 2.2.7 on 2019-12-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0005_auto_20191213_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='resume',
            field=models.FileField(default='default.pdf', upload_to='resumes'),
        ),
    ]
