# Generated by Django 2.2.7 on 2019-12-13 14:13

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0006_candidate_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='mobile_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(default='default.pdf', null=True, upload_to='resumes'),
        ),
    ]
