# Generated by Django 2.2.7 on 2019-12-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0007_auto_20191213_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='mobile_number',
            field=models.CharField(max_length=100),
        ),
    ]
