# Generated by Django 2.2.7 on 2019-12-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0012_auto_20191215_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
