# Generated by Django 2.2.7 on 2019-12-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0013_auto_20191215_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='count',
            field=models.IntegerField(default=0, max_length=3),
        ),
    ]
