# Generated by Django 3.0 on 2019-12-19 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0014_candidate_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidate_codes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_code', models.TextField(max_length=1000000)),
                ('cpp_code', models.TextField(max_length=1000000)),
                ('csharp_code', models.TextField(max_length=1000000)),
                ('java_code', models.TextField(max_length=1000000)),
                ('python_code', models.TextField(max_length=1000000)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.Candidate')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.Question')),
            ],
        ),
    ]
