# Generated by Django 3.0 on 2019-12-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0015_candidate_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_codes',
            name='c_code',
            field=models.TextField(default='', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='candidate_codes',
            name='cpp_code',
            field=models.TextField(default='', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='candidate_codes',
            name='csharp_code',
            field=models.TextField(default='', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='candidate_codes',
            name='java_code',
            field=models.TextField(default='', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='candidate_codes',
            name='python_code',
            field=models.TextField(default='', max_length=1000000),
        ),
    ]
