# Generated by Django 3.0 on 2019-12-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0016_auto_20191219_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_codes',
            name='c_code',
            field=models.TextField(default='#include<stdio.h>\n\nint main() {\n    \n    printf("");\n    \n}\n', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='candidate_codes',
            name='cpp_code',
            field=models.TextField(default='#include <iostream>\n\nusing namespace std;\n\nint main() {\n    \n    cout<<"" << ;\n}\n', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='candidate_codes',
            name='csharp_code',
            field=models.TextField(default='//Note don\'t change the class name \nusing System;\n\nclass Program\n{\n    static void Main() {\n        Console.Write("");\n    }\n}\n', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='candidate_codes',
            name='java_code',
            field=models.TextField(default='//NOTE: Don\'t change class name\npublic class MyClass {\n    public static void main(String args[]) {\n      System.out.println("" );\n    }\n}\n', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='candidate_codes',
            name='python_code',
            field=models.TextField(default="if __name__ == '__main__' in python:\n", max_length=1000000),
        ),
    ]
