# Generated by Django 3.0 on 2019-12-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0017_auto_20191219_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
