# Generated by Django 3.0 on 2019-12-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0018_auto_20191220_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='Duration',
        ),
        migrations.AddField(
            model_name='challenge',
            name='Test_Duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='Description',
            field=models.TextField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='question',
            name='sample_inputs',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='sample_outputs',
            field=models.TextField(max_length=500),
        ),
    ]
