# Generated by Django 3.0 on 2019-12-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0019_auto_20191220_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_codes',
            name='submitted_code',
            field=models.TextField(default='', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='candidate_codes',
            name='cpp_code',
            field=models.TextField(default='#include <iostream>\n\nusing namespace std;\n\nint main() {\n    \n    cout<<"";\n}\n', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='candidate_codes',
            name='python_code',
            field=models.TextField(default="if __name__ == '__main__':\n", max_length=1000000),
        ),
    ]
