# Generated by Django 3.0 on 2019-12-21 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0021_auto_20191222_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='Total_Score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate_codes',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
