# Generated by Django 3.0 on 2019-12-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0022_auto_20191222_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='completed_status',
            field=models.BooleanField(default=False),
        ),
    ]
